### ISSUE TITLE
PolINSAR to-do's

### ISSUE THREAD

**Issue by slumnitz** [BioPAL/BioPAL#21]
# Roadmap to PolINSAR and BioPAL public release

**Critical to-do's**:

* [x] website
    * [x] general content and infrastructure development for website (see https://github.com/BioPAL/biopal.org/issues/1)

* [x] Tutorial 
    * [x] starting Jupyter notebook example
        * [ ] Brief explanation of AGB science and algorithm (@imsoja, @francescobanda)
        * [ ] Brief high-level overview of entire BIOMASS processing chain (?) and place of AGB within the processing chain, i.e. through flow diagram (@francescobanda)
        * [x] Short introduction: How to run the algorithm (@francescobanda @imsoja)
        * [ ]  Static and dynamic visualization of results, potential interpretation analysis (@slumnitz )
     * [x] investigating Jupyter notebook change tracking setup (@slumnitz )
     * [x] investigate data/ tutorial environment on MAAP (@slumnitz @ClementAlbinet )

* [x] Biopal public release
* [x] check governance documents content (@slumnitz @kscipal @ClementAlbinet )
* [ ] check/ update Docker Hub image (@pmazzucchelli @francescobanda)

**Comment by slumnitz** [comment]
closing as successfully release on PolInSAR
